name: draggable_panel
description: A versatile floating panel widget that can be dragged around the screen and docked to edges. Perfect for displaying tools, actions, or additional content on demand.
version: 1.4.2
homepage: https://github.com/yelmuratoff/draggable_panel.git
issue_tracker: https://github.com/yelmuratoff/draggable_panel/issues

topics:
  - draggable-panel
  - draggable
  - panel
  - floating-panel
  - floating-button

environment:
  sdk: ^3.2.0
  flutter: "any"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
